// Generated by CoffeeScript 1.6.3
(function() {
  var Bob;

  Bob = (function() {
    function Bob() {}

    Bob.hey = function(phrase) {
      switch (false) {
        case !isSilent(phrase):
          return 'Fine, be that way.';
        case !isShouting(phrase):
          return 'Woah, chill out!';
        case !isAskingAQuestion(phrase):
          return 'Sure.';
        default:
          return 'Whatever.';
      }
    };

    Bob.isSilent = function(phrase) {
      return phrase === '';
    };

    Bob.isShouting = function(phrase) {
      return phrase.toUppercase === phrase;
    };

    Bob.isAskingAQuestion = function(phrase) {
      return /\?$/.test(phrase);
    };

    return Bob;

  })();

}).call(this);
