// Generated by CoffeeScript 1.6.3
(function() {
  var DNA;

  DNA = (function() {
    function DNA(sequence) {
      this.sequence = sequence;
    }

    DNA.prototype.toRNA = function() {
      return this.sequence.replace(/T/g, 'U');
    };

    return DNA;

  })();

  global.DNA = DNA;

}).call(this);
