// Generated by CoffeeScript 1.6.3
(function() {
  var Anagram, isAnagram, sortString;

  module.exports = Anagram = (function() {
    function Anagram(term) {
      this.sortedTerm = sortString(term.toLowerCase());
    }

    Anagram.prototype.match = function(words) {
      var matches, word, _i, _len;
      matches = [];
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        word = words[_i];
        if (isAnagram(word, this.sortedTerm)) {
          matches.push(word);
        }
      }
      return matches;
    };

    return Anagram;

  })();

  isAnagram = function(word, sortedTerm) {
    return sortString(word) === sortedTerm;
  };

  sortString = function(s) {
    return s.split('').sort().join('');
  };

}).call(this);
