// Generated by CoffeeScript 1.6.3
(function() {
  var Binary;

  Binary = require('./example');

  describe('binary', function() {
    it('1 is decimal 1', function() {
      return expect(1).toEqual(new Binary('1').toDecimal());
    });
    it('10 is decimal 2', function() {
      return expect(2).toEqual(new Binary('10').toDecimal());
    });
    it('11 is decimal 3', function() {
      return expect(3).toEqual(new Binary('11').toDecimal());
    });
    it('100 is decimal 4', function() {
      return expect(4).toEqual(new Binary('100').toDecimal());
    });
    it('1001 is decimal 9', function() {
      return expect(9).toEqual(new Binary('1001').toDecimal());
    });
    it('11010 is decimal 26', function() {
      return expect(26).toEqual(new Binary('11010').toDecimal());
    });
    it('10001101000 is decimal 1128', function() {
      return expect(1128).toEqual(new Binary('10001101000').toDecimal());
    });
    return it('carrot is decimal 0', function() {
      return expect(0).toEqual(new Binary('carrot').toDecimal());
    });
  });

}).call(this);
