// Generated by CoffeeScript 1.6.3
(function() {
  var Binary;

  module.exports = Binary = (function() {
    function Binary(binary) {
      this.binary = parseInt(binary, 2);
    }

    Binary.prototype.toDecimal = function() {
      var result;
      result = Number(this.binary.toString(10));
      if (isNaN(result)) {
        return 0;
      }
      return result;
    };

    return Binary;

  })();

}).call(this);
