// Generated by CoffeeScript 1.6.3
(function() {
  var Words;

  Words = (function() {
    function Words(phrase) {
      this.wordList = phrase.toLowerCase().split(/\W+/);
    }

    Words.count = function() {
      return {
        word: 1
      };
    };

    return Words;

  })();

}).call(this);
