// Generated by CoffeeScript 1.6.3
(function() {
  exports.wordCount = function(phrase) {
    var count, word, words, _i, _len;
    words = phrase.toLowerCase().match(/\w+/g);
    count = {};
    for (_i = 0, _len = words.length; _i < _len; _i++) {
      word = words[_i];
      if (!count.hasOwnProperty(word)) {
        count[word] = 0;
      }
      count[word] += 1;
    }
    return count;
  };

}).call(this);
