// Generated by CoffeeScript 1.6.3
(function() {
  var DNA;

  module.exports = DNA = (function() {
    function DNA(sequence) {
      this.sequence = sequence;
      this.nucleotideCounts = this.getNucleotideCounts();
    }

    DNA.prototype.count = function(nucleotide) {
      var NUCLEOTIDES;
      NUCLEOTIDES = "ACGTU";
      if (NUCLEOTIDES.indexOf(nucleotide) === -1) {
        throw new Error('Invalid Nucleotide');
      } else {
        return this.occurrencesOf(nucleotide);
      }
    };

    DNA.prototype.getNucleotideCounts = function() {
      return {
        A: this.count('A'),
        T: this.count('T'),
        C: this.count('C'),
        G: this.count('G')
      };
    };

    DNA.prototype.occurrencesOf = function(nucleotide) {
      return this.sequence.split(nucleotide).length - 1;
    };

    return DNA;

  })();

}).call(this);
