// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    sing: function(first, last) {
      var i, verses, _i;
      if (last == null) {
        last = 0;
      }
      verses = [];
      for (i = _i = first; first <= last ? _i <= last : _i >= last; i = first <= last ? ++_i : --_i) {
        verses.push(this.verse(i));
      }
      return verses.join("\n");
    },
    verse: function(n) {
      switch (n) {
        case 0:
          return "No more bottles of beer on the wall, no more bottles of beer.\nGo to the store and buy some more, 99 bottles of beer on the wall.\n";
        case 1:
          return "1 bottle of beer on the wall, 1 bottle of beer.\nTake it down and pass it around, no more bottles of beer on the wall.\n";
        case 2:
          return "2 bottles of beer on the wall, 2 bottles of beer.\nTake one down and pass it around, 1 bottle of beer on the wall.\n";
        default:
          return "" + n + " bottles of beer on the wall, " + n + " bottles of beer.\nTake one down and pass it around, " + (n - 1) + " bottles of beer on the wall.\n";
      }
    }
  };

}).call(this);
