// Generated by CoffeeScript 1.6.3
var isQuestion, isShout, isSilence;

exports.hey = function(phrase) {
  if (isSilence(phrase)) {
    return 'Fine. Be that way!';
  }
  if (isShout(phrase)) {
    return 'Woah, chill out!';
  }
  if (isQuestion(phrase)) {
    return 'Sure.';
  }
  return 'Whatever.';
};

isQuestion = function(phrase) {
  return phrase[phrase.length - 1] === '?';
};

isShout = function(phrase) {
  return phrase.toUpperCase() === phrase;
};

isSilence = function(phrase) {
  return !phrase || !phrase.trim();
};
